### ISSUE TITLE
Cesium chrashes after a while

### ISSUE THREAD

**Issue by nnhw** [Midgrad/Dreka#24]
qml: An error occurred while rendering.  Rendering has stopped.
RangeError: Invalid array length
RangeError: Invalid array length
    at updateFrustums (file:///tmp/Dreka/Debug/Cesium/Cesium.js:1:3101163)
    at View.createPotentiallyVisibleSet (file:///tmp/Dreka/Debug/Cesium/Cesium.js:1:3104047)
    at executeCommandsInViewport (file:///tmp/Dreka/Debug/Cesium/Cesium.js:1:3288675)
    at Scene.updateAndExecuteCommands (file:///tmp/Dreka/Debug/Cesium/Cesium.js:1:3285975)
    at render (file:///tmp/Dreka/Debug/Cesium/Cesium.js:1:3298515)
    at tryAndCatchError (file:///tmp/Dreka/Debug/Cesium/Cesium.js:1:3298752)
    at Scene.render (file:///tmp/Dreka/Debug/Cesium/Cesium.js:1:3300610)
    at CesiumWidget.render (file:///tmp/Dreka/Debug/Cesium/Cesium.js:1:3555274)
    at e (file:///tmp/Dreka/Debug/Cesium/Cesium.js:1:3540976)
qml: Uncaught RangeError: Invalid array length

![изображение](https://user-images.githubusercontent.com/37814163/131641279-72baecac-a972-4c22-a2d8-007d95443c5f.png)

**Comment by MishkaRogachev** [comment]
Some info:
https://github.com/CesiumGS/cesium/issues/1477
https://github.com/CesiumGS/cesium/issues/2317
https://github.com/CesiumGS/cesium/issues/8806

**Comment by MishkaRogachev** [comment]
https://github.com/Midgrad/Dreka/commit/d285b0084401e3bb68942b2afddd04dc0aa44259
